name: Algolia Docsearch Indexer

on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  indexer:
    runs-on: ubuntu-latest
    name: Indexer
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: '6V1I8J0EG'
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          file: algolia.config.json